# Generated by Django 6.0.2 on 2026-02-27 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('corn', 'Corn'), ('cotton', 'Cotton'), ('sugarcane', 'Sugarcane'), ('soybean', 'Soybean'), ('tomato', 'Tomato'), ('potato', 'Potato'), ('onion', 'Onion'), ('groundnut', 'Groundnut')], max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trend', models.CharField(choices=[('up', 'Rising'), ('down', 'Falling'), ('stable', 'Stable')], default='stable', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
