# Generated by Django 6.0.2 on 2026-03-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerlisting',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
